### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by happywch** [mzc421/NLP#7]
对于特定领域的意图识别，比如，家庭控制领域。
我是不是 不仅需要标注家庭控制领域内的相关数据集，还需要针对日常的无关的内容进行标注（比如“该吃饭了”），以防止误触
那么这种无关的内容该怎么标注呢。是单独将无关的内容全部标注为一个意图。还是直接空着。
当然我希望这种无关的内容可以尽可能的少的占用预测资源（不是训练）

**Comment by mzc421** [comment]
无关的内容可以有，也可以没有



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月11日 11:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [mzc421/NLP] 数据集 (Issue #7) |

对于特定领域的意图识别，比如，家庭控制领域。
我是不是 不仅需要标注家庭控制领域内的相关数据集，还需要针对日常的无关的内容进行标注（比如“该吃饭了”），以防止误触
那么这种无关的内容该怎么标注呢。是单独将无关的内容全部标注为一个意图。还是直接空着。
当然我希望这种无关的内容可以尽可能的少的占用预测资源（不是训练）

**Comment by mzc421** [comment]
按照你的实际用途，这个无关的应该是可以没有的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月11日 11:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [mzc421/NLP] 数据集 (Issue #7) |

对于特定领域的意图识别，比如，家庭控制领域。
我是不是 不仅需要标注家庭控制领域内的相关数据集，还需要针对日常的无关的内容进行标注（比如“该吃饭了”），以防止误触
那么这种无关的内容该怎么标注呢。是单独将无关的内容全部标注为一个意图。还是直接空着。
当然我希望这种无关的内容可以尽可能的少的占用预测资源（不是训练）
